// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_session_id_from_tempFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_session_id_from_tempFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201704251356247_remove_session_id_from_tempFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
