// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class required_name_for_interest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required_name_for_interest));
        
        string IMigrationMetadata.Id
        {
            get { return "201704201124249_required_name_for_interest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
