// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userreservationsreference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userreservationsreference));
        
        string IMigrationMetadata.Id
        {
            get { return "201704020512557_user-reservations-reference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
