// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class made_linked_object_required_for_picture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(made_linked_object_required_for_picture));
        
        string IMigrationMetadata.Id
        {
            get { return "201705010534554_made_linked_object_required_for_picture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
