// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_index_to_pictures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_index_to_pictures));
        
        string IMigrationMetadata.Id
        {
            get { return "201801240432273_add_index_to_pictures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
